### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by prettend-s** [Dar9586/NClientV2#404] opened 2022-03-06 04:08 UTC
![Screenshot_2022-03-06-12-08-11-31_8dc4a708c34f1c510344fe919321c07b](https://user-images.githubusercontent.com/99039892/156908832-3abc5f21-ee9b-4b86-b2ec-8c9298c1d6e0.jpg)

**Comment by Notarin** [comment] 2022-03-06 13:54
This is a duplicate of #402

**Closed** 2022-05-25 17:38 UTC

**Comment by Notarin** [comment] 2022-05-27 06:52
please label duplicate, ty
