### ISSUE TITLE
App force closed when tap setting

### ISSUE THREAD

**Issue by hohommx2015** [Dar9586/NClientV2#181] opened 2020-06-26 07:07 UTC
After new update,cant enter setting anymore

**Comment by hmaltr** [comment] 2020-06-26 07:21
Try clearing the cache if it doesnt work try deleting the data. If that doesnt fix too reinstall could fix it. It seems the problem is on your side since i can use the settings without problems. And if it doesnt fix *if it comes that far* Can you post more details about your phone model, android version and if an SD card is existent.

**Comment by hohommx2015** [comment] 2020-06-26 12:12
Tried all methods,no luck.Downgraded to 2.4.3,all work fine.My phone is Meizu 16T/Android 9,SD card is present.

**Comment by hmaltr** [comment] 2020-06-26 12:52
Seems like an code problem. @Dar9586 Has to fix it in case.

**Comment by Dar9586** [comment] 2020-06-26 14:17
Fixed in 2.4.6

**Comment by hohommx2015** [comment] 2020-06-27 09:11
> Fixed in 2.4.6

Confirmed fixed,thanks.

**Closed** 2020-06-27 09:11 UTC
