### ISSUE TITLE
issue on downloads tab

### ISSUE THREAD

**Issue by aligdr** [Dar9586/NClientV2#278] opened 2021-02-02 08:50 UTC
App crashs on openning dowloads installing the new update

**Comment by Dar9586** [comment] 2021-02-02 09:59
Probabily duplicate of #277, if it is the case I reloaded the apk with the fix
https://github.com/Dar9586/NClientV2/releases/download/2.6.9/NClientV2.2.6.9.Release.apk
https://github.com/Dar9586/NClientV2/releases/download/2.6.9/NClientV2.2.6.9.Debug.apk

**Closed** 2021-02-04 10:05 UTC
