### ISSUE TITLE
no entries found

### ISSUE THREAD

**Issue by error40436194391** [Dar9586/NClientV2#403] opened 2022-03-06 03:31 UTC
no tags but still no entries found

**Comment by Notarin** [comment] 2022-03-06 13:55
This is a duplicate of #402

**Comment by Lucaelgar** [comment] 2022-03-08 06:38
> This is a duplicate of #402

shut up you tweep

**Comment by Notarin** [comment] 2022-03-08 08:50
> > This is a duplicate of #402
> 
> shut up you tweep

Take a chill pill kid. This isn't a forum this is a fucking GitHub issue. Go elsewhere with that shit.

**Comment by Lucaelgar** [comment] 2022-03-13 02:47
> > > This is a duplicate of #402
> > 
> > 
> > shut up you tweep
> 
> Take a chill pill kid. This isn't a forum this is a fucking GitHub issue. Go elsewhere with that shit.

yeah that's true

**Closed** 2022-05-25 17:38 UTC
Labels: duplicate
